### ISSUE TITLE
SWAGGER AUTO GENERATED API

### ISSUE THREAD

**Issue by jelordreygulle** [cdimascio/generator-express-no-stress#13]
Sir, is there a way to automate the api documentation instead of typing in manually ?

**Comment by cdimascio** [comment]
This project expects the user to create the specification via a yaml file. The framework then reads this specification and uses it to automatically perform request validation (so that you don't have to write that code) and serve interactive api documentation. There are other projects that can generate documentation, for example, from comments in the source code. That however is not the purpose of this project.
