### ISSUE TITLE
Getting yarn error on scaffold w/o using --yarn flag

### ISSUE THREAD

**Issue by alnjxn** [cdimascio/generator-express-no-stress#16]
I did a fresh global install of the package using npm as described in the docs. Getting the following error when running the generator. Not sure why a locakfile would exist before scaffolding a project, when not using `--yarn` flag. 

```
λ yo express-no-stress myapp
yarn outdated v1.5.1
error An unexpected error occurred: "No lockfile in this directory. Run `yarn install` to generate one.".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ajackson/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**Comment by cdimascio** [comment]
@alnjxn i am unable to reproduce this behavior. can you provide some additional details about your environment e.g. os, node version, yo version
fyi i ran my test on a mac book pro 2017 high sierra 10.13.3, node 8.9.3, yo 2.0.1

**Comment by cdimascio** [comment]
thank @alnjxn. i presume you were able to get it running successfully?

**Comment by alnjxn** [comment]
No. I just decided to not use the library. Didn't want to leave you with an open issue that I can't assist in tracking down.

**Comment by chrisandrewcl** [comment]
Just in case anyone bounces here: this is most likely due to a local alias conflicting with `yo` command.

To check, run `alias yo` or `type yo` to confirm. The output should be something like this:

    yo is an alias for yarn outdated

If so, you have basically two options: remove the conflicting alias or use `yeoman` command with a preceding backslash `\yo` (it skip the existing alias).
