### ISSUE TITLE
Debugging example

### ISSUE THREAD

**Issue by amygdaloideum** [cdimascio/generator-express-no-stress#6]
Is it possible to debug this project? Some pointers in the README regarding this would be useful!

**Comment by cdimascio** [comment]
Hey @amygdaloideum. Great idea! And thanks for the question. 
The answer is yes, it is possible. To do so, add the following target to npm scripts in `package.json`.
`"debug": "node build.js && backpack dev --inspect-brk | pino -o 'short'"`
Now you should be able to use your favorite inspector. I will get this added into the project. 
Hope this helps.

**Comment by amygdaloideum** [comment]
@cdimascio  When I use visual studio code I can only debug the bundled main.js file without source maps. Which inspector do you use?

**Comment by cdimascio** [comment]
vs code as well, try this... https://gist.github.com/cdimascio/51097a179c1a99e5b928740645506feb#file-node-8-with-babel-vscode

**Comment by amygdaloideum** [comment]
Thank you! Can I ask, is there any benefit of using backpack instead of just using es6-modules with the --experimental-modules flag? Does the bundling actually help with anything?

**Comment by cdimascio** [comment]
@amygdaloideum if you are only looking for es-modules and no other features provided by babel, you can certainly get by without backpack or babel. to do so, you'll have to remove those related files and update the scripts package.json. 

If you go down this path, please provide those changes to me, or better yet submit a PR with the changes. I may consider adding an option to either transpile i.e use the current setup with babel+backpack and es.next or to not transpile and instead use the installed version of node (and its current features, experimental included) as is.

Note, the reason is that currently this is an either or choice since Babel does not yet support the --experimental-modules flag see https://github.com/babel/babel/issues/6285.

**Comment by cdimascio** [comment]
Fixed by @amygdaloideum https://github.com/cdimascio/generator-express-no-stress/pull/8
